spring.application.name=preto_back

# Encoding
spring.messages.encoding=utf-8

# Active profile
spring.profiles.active=dev

# Jackson dates formatting
spring.jackson.serialization.write-dates-as-timestamps=false